### PR TITLE
draws regular hexagon

### PR DESCRIPTION
**Pull request by ZachDykstra**

### CODE REVIEW

**Comment by jonathoncihlar** [comment]
I'll merge this in, but make sure to add a test to MoHiGraphicsTester

**Comment by ZachDykstra** [comment]
I did add a test to MoHiGraphicsTester, and it worked properly. I can still
see the output from the test I wrote, so maybe it just wasn't pushed over
because I only added the code I changed in MoHiGraphics.java before
committing and pushing it over.

**Comment by jonathoncihlar** [comment]
It looks like it didn't get added to the commit that was pushed (you have to git add MoHIGraphicsTester.java) . To keep things clean, create a new branch, add that file to the commit. Do the commit and push. Then pull request. I'll take it from there.

**Comment by ZachDykstra** [comment]
Do I need to add MoHiGraphics.java also, or just the tester file?

**Comment by jonathoncihlar** [comment]
You will just need the tester file.

**Comment by ZachDykstra** [comment]
I made the pull request after pushing through the tester code within a new
branch named "hexagonTester"

**Pull request merged**
